# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flashtalk_streaming.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'flashtalk_streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x66lashtalk_streaming.proto\x12\x15sglang.multimodal_gen\")\n\x13StreamFramesRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\xa3\x01\n\x0b\x46ramePacket\x12\x13\n\x0b\x63hunk_index\x18\x01 \x01(\r\x12\x11\n\th264_data\x18\x02 \x01(\x0c\x12\x11\n\tpcm_audio\x18\x03 \x01(\x0c\x12\x0e\n\x06pts_ms\x18\x04 \x01(\x04\x12\x13\n\x0bis_keyframe\x18\x05 \x01(\x08\x12\x34\n\nvideo_meta\x18\x06 \x01(\x0b\x32 .sglang.multimodal_gen.VideoMeta\"Q\n\tVideoMeta\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x0b\n\x03\x66ps\x18\x03 \x01(\r\x12\x18\n\x10\x63odec_extra_data\x18\x04 \x01(\x0c\x32x\n\x12\x46lashTalkStreaming\x12\x62\n\x0cStreamFrames\x12*.sglang.multimodal_gen.StreamFramesRequest\x1a\".sglang.multimodal_gen.FramePacket\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flashtalk_streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMFRAMESREQUEST']._serialized_start=52
  _globals['_STREAMFRAMESREQUEST']._serialized_end=93
  _globals['_FRAMEPACKET']._serialized_start=96
  _globals['_FRAMEPACKET']._serialized_end=259
  _globals['_VIDEOMETA']._serialized_start=261
  _globals['_VIDEOMETA']._serialized_end=342
  _globals['_FLASHTALKSTREAMING']._serialized_start=344
  _globals['_FLASHTALKSTREAMING']._serialized_end=464
# @@protoc_insertion_point(module_scope)
