# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from sglang.multimodal_gen.grpc import flashtalk_streaming_pb2 as flashtalk__streaming__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in flashtalk_streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FlashTalkStreamingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamFrames = channel.unary_stream(
                '/sglang.multimodal_gen.FlashTalkStreaming/StreamFrames',
                request_serializer=flashtalk__streaming__pb2.StreamFramesRequest.SerializeToString,
                response_deserializer=flashtalk__streaming__pb2.FramePacket.FromString,
                _registered_method=True)


class FlashTalkStreamingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamFrames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlashTalkStreamingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamFrames': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFrames,
                    request_deserializer=flashtalk__streaming__pb2.StreamFramesRequest.FromString,
                    response_serializer=flashtalk__streaming__pb2.FramePacket.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sglang.multimodal_gen.FlashTalkStreaming', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sglang.multimodal_gen.FlashTalkStreaming', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FlashTalkStreaming(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sglang.multimodal_gen.FlashTalkStreaming/StreamFrames',
            flashtalk__streaming__pb2.StreamFramesRequest.SerializeToString,
            flashtalk__streaming__pb2.FramePacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
